// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrHKGe5v1TcKNtkFZ6ToOja33ziRgp_YA',
    appId: '1:699399530829:web:70b694858ebc0bb4f02f04',
    messagingSenderId: '699399530829',
    projectId: 'care-companion-43428',
    authDomain: 'care-companion-43428.firebaseapp.com',
    storageBucket: 'care-companion-43428.firebasestorage.app',
    measurementId: 'G-6EQFW8F3JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz_OAkN8GxzoG4Ybn7PHy4Q-1Kru_4n7Y',
    appId: '1:699399530829:android:7bf652bbde28b61ef02f04',
    messagingSenderId: '699399530829',
    projectId: 'care-companion-43428',
    storageBucket: 'care-companion-43428.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5T_rRZN-NQ2OnYQ_n_0bMie5Ep0wSUMA',
    appId: '1:699399530829:ios:02145ac4cc108cc0f02f04',
    messagingSenderId: '699399530829',
    projectId: 'care-companion-43428',
    storageBucket: 'care-companion-43428.firebasestorage.app',
    iosBundleId: 'com.jaisachdeva.carecompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5T_rRZN-NQ2OnYQ_n_0bMie5Ep0wSUMA',
    appId: '1:699399530829:ios:a92a37177188754bf02f04',
    messagingSenderId: '699399530829',
    projectId: 'care-companion-43428',
    storageBucket: 'care-companion-43428.firebasestorage.app',
    iosBundleId: 'com.example.careCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrHKGe5v1TcKNtkFZ6ToOja33ziRgp_YA',
    appId: '1:699399530829:web:cfc754313e6f3c03f02f04',
    messagingSenderId: '699399530829',
    projectId: 'care-companion-43428',
    authDomain: 'care-companion-43428.firebaseapp.com',
    storageBucket: 'care-companion-43428.firebasestorage.app',
    measurementId: 'G-EGMYN8C06N',
  );
}
